
@startuml

package "Bank Statements" {
    [Bank Statement 1]
    [Bank Statement 2]
    [Bank Statement 3]
}

database "Data Base" {
    [Category]
    [Transaction]
    [Statement]
}

package "Income Category" {
    [Full Time Job]
    [Investments]
    [Misc]
}

package "Expenses Category" {
    [Amazon]
    [Food Takeaway]
    [Food Shoping]
    [Transport]
    [Etc]
}

package "Investment Category"{
    [T212]
    [Coinbase]
}

package "Savings Category"{
    [Personal Savings Account]
    [Joint Savings Account]
}

[Bank Statement 1]-->[WebServer]
[Bank Statement 2]-->[WebServer]
[Bank Statement 3]-->[WebServer]

[DataParser]-->[Transaction]

[Category]-->[Amazon]
[Category]-->[Food Shoping]
[Category]-->[Food Takeaway]
[Category]-->[Transport]
[Category]-->[Etc]

[Category]-->[Full Time Job]
[Category]-->[Investments]
[Category]-->[Misc]

[Category]-->[T212]
[Category]-->[Coinbase]

[Category]-->[Personal Savings Account]
[Category]-->[Joint Savings Account]

[WebServer]-->[Statement]
[WebServer]-->[DataParser]

@enduml



